import { Lexend } from "next/font/google";
import "./globals.css";
import { cn } from "./utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lexend = Lexend({
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("antialiased", lexend.className)}>{children}</body>
    </html>
  );
}
